# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TStan
email: travis_stanley@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test site to go through the process of hosting a website. It is intended to help me work on my skills as a developer. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tstan.me" # the base hostname & protocol for your site
twitter_username: tweetstan12
github_username:  TStan12

# Build settings
markdown: kramdown
